# POPS settings
STUDY_SCHEMA: 'spring_2022'
DB_SYS: 'postgresql'
PG_DB: "sandag_hts"
PG_HOST: "pops.rsginc.com"
PG_PORT: 5432

# Processing inputs/outputs
TABLES:
  household:
    name: w_rm_hh
    index: hh_id
  person: 
    name: w_rm_person
    index: person_id
  trip:
    name: w_rm_trip
    index: trip_id
  day: 
    name: w_rm_day
    index: day_id
  codebook: 
    name: w_value_labels 
    index: name

# Model steps to run
STEPS:
  - create_tours
  - flag_unreported_joint_trips
  - impute_reported_joint_trips
  # - impute_school_trips

# If commented out, data will not be stored locally
RESUME_AFTER: True # It will resume using the last processed step
CACHE_DIR: 'cache'
# OUTPUT_DIR: 'output'

# Codes used to filter data on, provide the column name and the values.
# The purpose is to allow column names to vary while maintaining code stability.

CODES:
# Non-adults <18 years old
  CHILD_AGE: 
    age: [1, 2, 3]
# Code for <5 years old
  PRESCHOOL_AGE: 
    age: [1]
# Code for pre-school school types
  PRESCHOOL_TYPES:
    school_type: [2, 3]
# Code for K-12 and preschool trip purposes
  SCHOOL_PURPOSES:
    d_purpose: [3, 21, 26]
# Purpose code for home
  HOME_PURPOSE: 
    ORIGIN:
      o_purpose: 1
    DESTINATION:
      d_purpose: 1

JOINT_TRIP_BUFFER:
  DISTANCE: 1000 # Feet
  TIME: 15 # Minutes

# In case there are non-default column names
# COLUMN_NAMES:
#   DAYNUM: day_num
#   OLAT: o_lat
#   OLON: o_lon
#   DLAT: d_lat
#   DLON: d_lon

